root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp/sintropia-air"

[build]
  args_bin = []
  bin = "/tmp/sintropia-air/main"
  cmd = "go build -o /tmp/sintropia-air/main ./cmd/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false

# Configuración específica para Go 1.24
[env]
  GO111MODULE = "on"
  GOPROXY = "https://proxy.golang.org,direct"
  GOSUMDB = "sum.golang.org"
  PORT = "3000"
  GIN_MODE = "debug"
  CORS_ALLOW_ALL = "true"